<?php

declare(strict_types=1);

/**
 * Famous game studios and publishers.
 *
 * @return array<string, string>
 */
return [
    // Major Publishers
    'Ubisoft' => '/\bUbisoft(?:\s+(?:Montreal|Quebec|Paris|Toronto|Singapore|Sofia|Bordeaux|Montpellier))?\b/iu',
    'Square Enix' => '/\bSquare\s*Enix\b/iu',
    'Rockstar' => '/\bRockstar(?:\s+(?:Games|North|San\s+Diego|Leeds|Toronto|India|Lincoln|New\s+England))?\b/iu',
    'Electronic Arts' => '/\bElectronic\s+Arts\b/iu',
    'EA' => '/\bEA(?:\s+(?:Sports|Games|Play|DICE|Motive))?\b/u',
    'Activision' => '/\bActivision(?:\s+Blizzard)?\b/iu',
    'Blizzard' => '/\bBlizzard(?:\s+Entertainment)?\b/iu',
    'Bethesda' => '/\bBethesda(?:\s+(?:Game\s+Studios|Softworks))?\b/iu',
    'CD Projekt' => '/\bCD\s*Projekt(?:\s+Red)?\b/iu',
    'Capcom' => '/\bCapcom\b/iu',
    'Konami' => '/\bKonami\b/iu',
    'Bandai Namco' => '/\bBandai\s*Namco(?:\s+(?:Entertainment|Studios))?\b/iu',
    'Sega' => '/\bSega\b/iu',
    'FromSoftware' => '/\bFromSoftware\b/iu',
    'From Software' => '/\bFrom\s+Software\b/iu',
    'Take-Two' => '/\bTake-?Two(?:\s+Interactive)?\b/iu',
    'Warner Bros' => '/\bWarner\s*Bros(?:\.\s*|\s+)?(?:Games|Interactive)?\b/iu',
    '2K Games' => '/\b2K(?:\s+Games)?\b/iu',
    'THQ Nordic' => '/\bTHQ(?:\s+Nordic)?\b/iu',
    'Deep Silver' => '/\bDeep\s+Silver\b/iu',
    'Focus Entertainment' => '/\bFocus(?:\s+(?:Entertainment|Interactive|Home\s+Interactive))?\b/iu',
    'Devolver Digital' => '/\bDevolver(?:\s+Digital)?\b/iu',
    'Annapurna' => '/\bAnnapurna(?:\s+Interactive)?\b/iu',

    // Sony Studios
    'Naughty Dog' => '/\bNaughty\s+Dog\b/iu',
    'Insomniac' => '/\bInsomniac(?:\s+Games)?\b/iu',
    'Santa Monica Studio' => '/\bSanta\s+Monica(?:\s+Studio)?\b/iu',
    'Guerrilla' => '/\bGuerrilla(?:\s+Games)?\b/iu',
    'Sucker Punch' => '/\bSucker\s+Punch(?:\s+Productions)?\b/iu',
    'Polyphony Digital' => '/\bPolyphony(?:\s+Digital)?\b/iu',
    'Bluepoint' => '/\bBluepoint(?:\s+Games)?\b/iu',
    'Housemarque' => '/\bHousemarque\b/iu',
    'Firesprite' => '/\bFiresprite\b/iu',

    // Microsoft Studios
    'Xbox Game Studios' => '/\bXbox\s+Game\s+Studios\b/iu',
    '343 Industries' => '/\b343\s*Industries\b/iu',
    'The Coalition' => '/\bThe\s+Coalition\b/iu',
    'Turn 10' => '/\bTurn\s*10(?:\s+Studios)?\b/iu',
    'Playground Games' => '/\bPlayground(?:\s+Games)?\b/iu',
    'Obsidian' => '/\bObsidian(?:\s+Entertainment)?\b/iu',
    'Double Fine' => '/\bDouble\s+Fine(?:\s+Productions)?\b/iu',
    'Ninja Theory' => '/\bNinja\s+Theory\b/iu',
    'Rare' => '/\bRare(?:\s+Ltd\.?)?\b/iu',
    'Compulsion Games' => '/\bCompulsion(?:\s+Games)?\b/iu',
    'inXile' => '/\binXile(?:\s+Entertainment)?\b/iu',

    // EA Studios
    'BioWare' => '/\bBioWare\b/iu',
    'DICE' => '/\bDICE\b/u',
    'Respawn' => '/\bRespawn(?:\s+Entertainment)?\b/iu',
    'Motive Studio' => '/\bMotive(?:\s+Studio)?\b/iu',
    'Criterion' => '/\bCriterion(?:\s+Games)?\b/iu',
    'Codemasters' => '/\bCodemasters\b/iu',

    // Other Major Studios
    'Bungie' => '/\bBungie\b/iu',
    'id Software' => '/\bid\s+Software\b/iu',
    'Remedy' => '/\bRemedy(?:\s+Entertainment)?\b/iu',
    'Team Ninja' => '/\bTeam\s+Ninja\b/iu',
    'PlatinumGames' => '/\bPlatinumGames\b/iu',
    'Platinum Games' => '/\bPlatinum\s+Games\b/iu',
    'Arc System Works' => '/\bArc\s+System\s+Works\b/iu',
    'NetherRealm' => '/\bNetherRealm(?:\s+Studios)?\b/iu',
    'Larian' => '/\bLarian(?:\s+Studios)?\b/iu',
    'Techland' => '/\bTechland\b/iu',
    'IO Interactive' => '/\bIO\s+Interactive\b/iu',
    'Avalanche' => '/\bAvalanche(?:\s+(?:Studios|Software))?\b/iu',
    'MachineGames' => '/\bMachineGames\b/iu',
    'Machine Games' => '/\bMachine\s+Games\b/iu',
    'Arkane' => '/\bArkane(?:\s+(?:Studios|Lyon|Austin))?\b/iu',
    'Tango Gameworks' => '/\bTango\s+Gameworks\b/iu',
    'Asobo' => '/\bAsobo(?:\s+Studio)?\b/iu',
    'Rebellion' => '/\bRebellion(?:\s+Developments)?\b/iu',
    'Gearbox' => '/\bGearbox(?:\s+(?:Software|Entertainment))?\b/iu',
    'Supergiant' => '/\bSupergiant(?:\s+Games)?\b/iu',
    'Team Cherry' => '/\bTeam\s+Cherry\b/iu',
    'Moon Studios' => '/\bMoon\s+Studios\b/iu',
    'ConcernedApe' => '/\bConcernedApe\b/iu',
    'Re-Logic' => '/\bRe-?Logic\b/iu',
    'Coffee Stain' => '/\bCoffee\s+Stain(?:\s+Studios)?\b/iu',
    'Grinding Gear' => '/\bGrinding\s+Gear(?:\s+Games)?\b/iu',
    'Digital Extremes' => '/\bDigital\s+Extremes\b/iu',
    'Fatshark' => '/\bFatshark\b/iu',
    'Paradox' => '/\bParadox(?:\s+(?:Interactive|Development\s+Studio))?\b/iu',
    'Creative Assembly' => '/\bCreative\s+Assembly\b/iu',
    'Relic' => '/\bRelic(?:\s+Entertainment)?\b/iu',
    'Amplitude' => '/\bAmplitude(?:\s+Studios)?\b/iu',
    'Firaxis' => '/\bFiraxis(?:\s+Games)?\b/iu',
    'Arrowhead' => '/\bArrowhead(?:\s+Game\s+Studios)?\b/iu',
    'Pocketpair' => '/\bPocketpair\b/iu',
    'Game Freak' => '/\bGame\s+Freak\b/iu',
    'Atlus' => '/\bAtlus\b/iu',
    'Koei Tecmo' => '/\bKoei\s*Tecmo\b/iu',
    'Level-5' => '/\bLevel-?5\b/iu',
    'Spike Chunsoft' => '/\bSpike\s+Chunsoft\b/iu',
    'NIS America' => '/\bNIS(?:\s+America)?\b/iu',
    'Nippon Ichi' => '/\bNippon\s+Ichi(?:\s+Software)?\b/iu',
    'Marvelous' => '/\bMarvelous(?:\s+(?:Entertainment|Inc\.?))?\b/iu',
    'Grasshopper' => '/\bGrasshopper(?:\s+Manufacture)?\b/iu',
    'Shift Up' => '/\bShift\s+Up\b/iu',
];
